### PR TITLE
TypeTree speedup shiftindicies

### PR DESCRIPTION
**Pull request by wsmoses**
Fixes https://github.com/EnzymeAD/Enzyme/issues/1743

### CODE REVIEW

**Comment by wsmoses** [comment]
note I left the slow version right now to do correctness tests, which already found a bug locally (which have fixed). Going to run it on the whole test suite, then disable the check once it comes back valid.

**Comment by wsmoses** [comment]
Also note this fix hopefully changes the asymptotic behavior of ShiftIndices from $O(n^2)$ to $O(n)$ [which it really should've been the whole time]

**Comment by vchuravy** [comment]
Seems like a speedup from 220s to 180s, but `TypeTree::insert` and `TypeTree:checkedOrIn` are still very hot

Before:

image


After:

image

image

Detailed analysis:

- `checkedOrIn` ~28s (42% of compilation time)
    - 17s from update Analysis 
    - 10.5s from EnzymeMergeTypeTree
- `CanonicalizeInPlace`: 11s

**Comment by ZuseZ4** [comment]
@vchuravy If already at it, could you please also profile 
https://github.com/EnzymeAD/Enzyme/pull/1641 if you have a few minutes? My server never had the permissions for vtune. My new Laptop is reasonable otherwise, so I can also set it up myself

**Comment by wsmoses** [comment]
Considering I don’t see ShiftIndices more on the flame graph I’m going to
call this a win.

I’ll see what I can do about the Julia function. mergeTypeTree is the C API
and primarily used in that function so I think it’s the next most
meaningful place we should be able to reduce overhead from. Essentially
because it should be not terrible to make it called only once. CheckedOrIn
however doesn’t have any obvious speed ups I remember.

**Pull request merged**
