### PR TITLE
Tblgen bugfix

### PR DESCRIPTION
**Pull request by ZuseZ4**

### CODE REVIEW

**Review by wsmoses — APPROVED** [review]
add a test just to prevent regression again?

**Comment by ZuseZ4** [comment]
I don't know Gaurav's handle to cc him :P

**Comment by wsmoses** [comment]
I think you should be able to do it with a code that is essentially

```
f(sizes, ...) {
a[1] = 
for (i; i<N; ) {
  lda = sizes[i];
  ...
   gemv(...);
}
}
```

try an llvm case like that and see if it crashes before but not now?

if not may

**Comment by wsmoses** [comment]
@ZuseZ4 also macos CI looks broken?

**Comment by ZuseZ4** [comment]
> @ZuseZ4 also macos CI looks broken?

I feel like we've been here before..

**Comment by wsmoses** [comment]
bumping @ZuseZ4 for merging

**Comment by ZuseZ4** [comment]
@wsmoses Wasn't able to reproduce yet. Can you take a stab at the tree issue and I go for this one?

**Comment by ZuseZ4** [comment]
following code compiles fine on main.
```
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#include "cblas.h"

double foo(int* lds, double *restrict K, double *restrict m, double *restrict x0, double *restrict v0, double T, int N) {
        int sX = 1;
        int sY = 1;
        double *pA = K;
        pA[0] = 42.0;
        double *pX = x0;
        double *pY = v0;
        double dt = 1.0 / 5000.0;
        for (size_t i = 0; i < 5000; i++) {
                int ld = lds[i % 32];
         cblas_dgemv(CblasRowMajor, CblasNoTrans, N, N, dt,
                         pA, ld, pX, sX, 
                         1.0, pY, sY);
         for (size_t j = 0; j < N; j++) 
           pX[j] += pY[j] * dt;
        }
        return pX[0];
}


extern void __enzyme_autodiff(void*, ...);
int enzyme_dup;
int enzyme_out;
int enzyme_const;

int main(int argc, char **argv) {
    int N = 200;
    double *K = (double*) calloc(N*N, sizeof(double));
    double *dK = (double*) calloc(N*N, sizeof(double));
    for (size_t i = 0; i < N; i++) {
      for (size_t j = 0; j < N; j++) {
         if (i == j) continue;
         K[i*N+j] = rand() / (RAND_MAX + 1.);
      }
    }
    //K = rand(N, N)
    //K[diagind(K)] .= 0
    double *m = (double*) calloc(N, sizeof(double));
    for (size_t i = 0; i < N; i++) {
      m[i] = 0.5 + rand() / (RAND_MAX + 1.);
    }
    //m = 0.5 .+ 0.5 * rand(N)
    double *x0 = (double*) calloc(N, sizeof(double));
    for (size_t i = 0; i < N; i++) {
      x0[i] = rand() / (RAND_MAX + 1.);
    }
    //x0 = randn(N)
    double *dx0 = (double*) calloc(N, sizeof(double));
    double *v0 = (double*) calloc(N, sizeof(double));//zeros(N)
    double *dv0 = (double*) calloc(N, sizeof(double));//zeros(N)
    double T = 1.0;
    int *lds = (int*) calloc(32, sizeof(int));
    for (size_t i = 0; i < 32; i++) {
      if (argc < 5) {
        lds[i] = 0;
      } else {
        lds[i] = i;
      }
    }

    __enzyme_autodiff((void*) foo, enzyme_const, lds, enzyme_dup, K, dK, enzyme_const, m, enzyme_dup, x0, dx0, enzyme_dup, v0, dv0, enzyme_const, T, N);
    printf("K: %f\n", K[1]);
    printf(" %f\n", dv0[0]);
}
```

**Pull request merged**
