### PR TITLE
Add nixpkgs to README

### PR DESCRIPTION
**Pull request by kiranshila**
I just finished up merging Enzyme into nixpkgs, so I thought a mention in the README might be useful

https://search.nixos.org/packages?channel=unstable&show=enzyme&from=0&size=50&sort=relevance&type=packages&query=enzyme

Like spack, nix is really handy for deterministic builds and setting up ephemeral dev environments with all the dependencies baked in.

For example, with nix you can do something like
```nix
(
  system: let
    pkgs = import nixpkgs {inherit system;};
    buildInputs = with pkgs; [enzyme cmake llvmPackages.bintools];
  in
    with pkgs; {
      devShells.default = mkShell.override {stdenv = clangStdenv;} {
        inherit buildInputs;
      };
    }
);
```
and prepare an environment with everything you need already built and linked together to develop with Enzyme!

### CODE REVIEW

**Comment by wsmoses** [comment]
Oh yeah definitely!

also feel free to add it to the website too which is at EnzymeAD/www

**Review by wsmoses — APPROVED** [review]

**Comment by wsmoses** [comment]
If you’d like we also have some scripts that automatically run each tag if it would be useful to run those to update the nix packages too

**Comment by kiranshila** [comment]
The nix CI stuff already auto pulls updates from github releases, somehow haha

**Comment by kiranshila** [comment]
Like this one https://github.com/NixOS/nixpkgs/pull/368158

**Pull request merged**
