### PR TITLE
Add tblgen BLAS support

### PR DESCRIPTION
**Pull request by ZuseZ4**
[x] emit missing flags for some args
[x] update tests
[x] adjust d_alpha update (not a pure blas call)
[] add new tests for axpy and scal

### CODE REVIEW

**Comment by ZuseZ4** [comment]
AdjointGenerator<AugmentedReturnType>::applyChainRule is unhappy and I need to add more test, other than that it looks fine.
I will remove enzyme/Enzyme/targets/BlasExampleGenerated.cpp before merging, just as a helper for review.

**Comment by ZuseZ4** [comment]
At least the dot tests only seem to be a matter of dot(x,y) vs. dot(y,x).

**Comment by ZuseZ4** [comment]
@tgymnich I can't reproduce the Debug segfaults, not even using the llvm-12 docker and debug build. Any further recommendations to reproduce CI?

**Comment by ZuseZ4** [comment]
The failing line is 
```.cpp
     Value *dif = diffe(&call, Builder2);
```
which is strange, since I only handle the BLAS functions further if the call is active, the line also works for dot which passes the test.
```.ll
➜  buildLLVMDbgEnzymeDbg git:(tg-blas2) ✗ /home/drehwald/prog/llvm-14/buildDebug/./bin/opt < /home/drehwald/prog/Enzyme/enzyme/test/Enzyme/ReverseMode/blas/alpha.ll  --enable-new-pm=0 -load=/home/drehwald/prog/Enzyme/enzyme/build/Enzyme/LLVMEnzyme-14.so --enzyme-attributor=0 -enzyme -mem2reg -instsimplify -simplifycfg -S
; Function Attrs: mustprogress willreturn
define internal { float } @diffef(i32 %len, float %a, float* noalias %x, float* %"x'", i32 %incx) #0 {
entry:
  call void @cblas_sscal(i32 %len, float %a, float* %x, i32 %incx) #0
  br label %invertentry

allocsForInversion:                               ; No predecessors!

invertentry:                                      ; preds = %entry
}

  call void @cblas_sscal(i32 %len, float %a, float* %x, i32 %incx) #0
opt: /home/drehwald/prog/Enzyme/enzyme/Enzyme/GradientUtils.h:2053: llvm::Value *DiffeGradientUtils::diffe(llvm::Value *, IRBuilder<> &): Assertion `0 && "getting diffe of constant value"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/drehwald/prog/llvm-14/buildDebug/./bin/opt --enable-new-pm=0 -load=/home/drehwald/prog/Enzyme/enzyme/build/Enzyme/LLVMEnzyme-14.so --enzyme-attributor=0 -enzyme -mem2reg -instsimplify -simplifycfg -S
1.	Running pass 'Enzyme Pass' on module '<stdin>'.
 #0 0x0000000004bf9eea llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/drehwald/prog/llvm-14/llvm/lib/Support/Unix/Signals.inc:565:11
 #1 0x0000000004bfa09b PrintStackTraceSignalHandler(void*) /home/drehwald/prog/llvm-14/llvm/lib/Support/Unix/Signals.inc:632:1
 #2 0x0000000004bf874a llvm::sys::RunSignalHandlers() /home/drehwald/prog/llvm-14/llvm/lib/Support/Signals.cpp:97:5
 #3 0x0000000004bfa7c5 SignalHandler(int) /home/drehwald/prog/llvm-14/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007f3282477520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x00007f32824cba7c __pthread_kill_implementation ./nptl/./nptl/pthread_kill.c:44:76
 #6 0x00007f32824cba7c __pthread_kill_internal ./nptl/./nptl/pthread_kill.c:78:10
 #7 0x00007f32824cba7c pthread_kill ./nptl/./nptl/pthread_kill.c:89:10
 #8 0x00007f3282477476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #9 0x00007f328245d7f3 abort ./stdlib/./stdlib/abort.c:81:7
#10 0x00007f328245d71b _nl_load_domain ./intl/./intl/loadmsgcat.c:1177:9
#11 0x00007f328246ee96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#12 0x00007f3281f8e72a DiffeGradientUtils::diffe(llvm::Value*, llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>&) /home/drehwald/prog/Enzyme/enzyme/Enzyme/GradientUtils.h:0:7
#13 0x00007f328217379e AdjointGenerator<AugmentedReturn const*>::diffe(llvm::Value*, llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>&) /home/drehwald/prog/Enzyme/enzyme/Enzyme/AdjointGenerator.h:1889:5
#14 0x00007f32821fa6c1 AdjointGenerator<AugmentedReturn const*>::handle_scal(AdjointGenerator<AugmentedReturn const*>::BlasInfo, llvm::CallInst&, llvm::Function*, std::map<llvm::Argument*, bool, std::less<llvm::Argument*>, std::allocator<std::pair<llvm::Argument* const, bool> > > const&, llvm::Type*) /home/drehwald/prog/Enzyme/enzyme/build/Enzyme/BlasDerivatives.inc:1452:12
```

**Comment by wsmoses** [comment]
The return _value_ of the call (a void type) is inactive, whereas the instruction is active.

**Pull request closed without merging**
