### PR TITLE
Update benchmark.yml

### PR DESCRIPTION
**Pull request by ZuseZ4**

### CODE REVIEW

**Comment by ZuseZ4** [comment]
@tgymnich Do you know why CI still isn't running this?

**Comment by tgymnich** [comment]
I don't think there are any openstack20 runners left. Try openstack22.

**Comment by ZuseZ4** [comment]
@tgymnich Doesn't seem to help much, any other ideas? Iirc there were so discussions about only running them on releases, since they were so slow, could that be an issue?

**Comment by tgymnich** [comment]
Workflow was disabled (in the GitHub UI under actions).

**Comment by ZuseZ4** [comment]
Is there a reason why we were benchmarking debug builds? Can I remove that option?

**Comment by wsmoses** [comment]
they currently all fail, if you can get them running before merging

**Comment by wsmoses** [comment]
@ZuseZ4 following up from slack convo, I don't see any of the tests here as passing?

**Comment by wsmoses** [comment]
In any case feel free to drop LLVM's before 15 for benchmarking, as we're going to do that shortly regardless

**Comment by ZuseZ4** [comment]
closing this since the current code has too many bugs, in favor of #2035 where I have more fixes

**Pull request closed without merging**
