### PR TITLE
use tg declarations to handle mat and vec dimensions

### PR DESCRIPTION
**Pull request by ZuseZ4**

### CODE REVIEW

**Comment by ZuseZ4** [comment]
@wsmoses are we sure that this is correct?
https://github.com/EnzymeAD/Enzyme/blob/c5a6954570b6929ac10cdd7f6c8b3c505ecab82c/enzyme/Enzyme/Utils.cpp#L2103
I just added handling for transposed matrices and my tests indicate that it's not.
I did modify the gemm_f_c_transpose_lacpy.ll testcase by setting transa to 'T' instead of 'N' (and A is modified, thus cached).

**Comment by wsmoses** [comment]
That code is wrong there should never be a builder nor any load or store
generated

**Comment by wsmoses** [comment]
The condition at the end should be return false at the end of the function
not return true

**Comment by wsmoses** [comment]
There should also be a continue after the for loop adding all the users
into todo

**Comment by ZuseZ4** [comment]
@wsmoses thanks. Behaves better now.

**Comment by ZuseZ4** [comment]
This now also has enough to remove this one: `(ld $A, $transa, $lda, $m, $n),`,
but since we already solved that I'll focus on nested rules before cleaning working code up.

**Review by wsmoses — APPROVED** [review]

**Comment by tgymnich** [comment]
this broke both macOS build and macOS tests

**Comment by ZuseZ4** [comment]
weren't they broken already for a while @tgymnich ?

**Comment by tgymnich** [comment]
Yeah i fixed them last WE. The Xcode build is the only one still broken.

**Pull request merged**
