### PR TITLE
New webpage

### PR DESCRIPTION
**Pull request by ludgerpaehler**
WIP

### CODE REVIEW

**Comment by ludgerpaehler** [comment]
- [ ] merge Doxygen docs into the webpage with [breath](https://breathe.readthedocs.io/en/latest/)e as a bridge between Sphinx and Doxygen. See: https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/

**Comment by ZuseZ4** [comment]
1) Not sure why, but for Firefox the header line (Enzyme Logo, Get Started, Languages, Resources, Github) 
has a different size on the starting page (index.html) compared to all other sites. This does not happen on chromium or on the PyTorch website. 

2) We don't use cookies, so I guess we are allowed to remove the banner stating that we don't use cookies? 
"We don't analyze traffic on this site via cookies."

**Comment by ludgerpaehler** [comment]
> * [ ]  merge Doxygen docs into the webpage with [breath](https://breathe.readthedocs.io/en/latest/)e as a bridge between Sphinx and Doxygen. See: https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/

Basic setup is there and functional, currently the `doxygenstruct` in `index.rst` is somehow not configured directly. To break it down:

1. `conf.py` launches a subprocess to carry out the doxygen command.
2.  `breathe` is configured to plug Doxygen files into Sphinx. With its configuration being at the bottom of the `conf.py` file.
3.  In `/docs/source/index.rst` we are defining the `doxygenstruct`, which is not functional so far. The error thrown is:

> ../../docs/source/index.rst:61: WARNING: doxygenstruct: Cannot find class "AdjointGenerator" in doxygen xml output for project "Enzyme" from directory: ../build/doxygen/xml/

**Comment by ludgerpaehler** [comment]
Current To-Do's:

Getting Started:
- [ ] Introduction to Automatic Differentiation
- [ ] Installation Instructions
- [ ] Link-time AD of Multi-Source Programs

Language Binding Docs:
- [ ] C/C++
- [ ] Fortran
- [ ] Rust
- [ ] Swift

User Manual:
- [ ] Troubleshooting and Tips
- [ ] Frequently Asked Questions
- [ ] Glossary
- [ ] Applications and Code Examples of Enzyme
- [ ] Talks and Tutorials

Advanced Features:
- [ ] MPI-Primitives
- [ ] OpenMP Directives and Constructs
- [ ] ROCm

**Comment by wsmoses** [comment]
This PR should be rebased against https://github.com/EnzymeAD/www as I believe I've successfully moved the website there. As a nice bonus this means we don't run all of Enzyme CI on website updates and vice versa (in addition to making it possible to directly host doxygen docs out of this repository).

**Pull request closed without merging**
