### PR TITLE
Fixed incorrect usage of llvm::Function::splice.

### PR DESCRIPTION
**Pull request by matinraayai**
cc: @wsmoses

### CODE REVIEW

**Comment by ivanradanov** [comment]
`Function::splice` seems to be unavailable in llvm 11, does the current approach break it some cases?

**Comment by wsmoses** [comment]
Sounds like we should ifdef the code there

**Comment by matinraayai** [comment]
It appears that `getBasicBlocks` function became private in LLVM 16. As Billy said, we have to `#ifdef` the code

**Comment by matinraayai** [comment]
@wsmoses I can fix the clang-format. Also I'm not sure what makes Bazel fail.

**Pull request merged**
