### PR TITLE
Move custom handler to preserve nvvm

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by tgymnich** [comment]
@wsmoses why does this belong to PreserveNVVM?

**Comment by wsmoses** [comment]
It needs to run as the first pass, since otherwise things could get inlined/etc.

**Comment by tgymnich** [comment]
Can we have a dedicated header for custom derivatives?

**Comment by wsmoses** [comment]
Yes, but in a separate PR as this fixes the currently broken existing
interface.

**Pull request merged**
