### PR TITLE
Ubuntu22

### PR DESCRIPTION
**Pull request by tgymnich**

### CODE REVIEW

**Comment by ZuseZ4** [comment]
Would it make sense to set up a kind of support policy in order to limit what we test (and thus especially CI time)?
18.04 is more than 4 yrs old and EOL in less than a year, so I wonder if we can't just replace it by 22.04?

**Comment by tgymnich** [comment]
Supporting ubuntu 18.04 until its EOL and replacing it with 22.04 sound like a good plan.

**Comment by tgymnich** [comment]
Failures in the integration tests for LLVM 11,12 and 13 in `Integration/ReverseMode/eigensumsqdyn-notmp.cpp`.
```
warning: <unknown>:0:0: failed to deduce type of copy   call void @llvm.memcpy.p0i8.p0i8.i64(i8* nonnull align 8 dereferenceable(32) %5, i8* nonnull align 8 dereferenceable(32) %6, i64 32, i1 false) #18
[599](https://github.com/EnzymeAD/Enzyme/runs/6832529792?check_suite_focus=true#step:7:600)
```

**Comment by wsmoses** [comment]
We should investigate the Type analysis failures to see if we can make them detectable/fixable.

Otherwise lgtm

**Comment by wsmoses** [comment]
The segfault from `Enzyme :: Integration/ReverseMode/integrateexp.cpp` needs to be fixed before merging. Anyone have time to investigate?

**Comment by tgymnich** [comment]
Mostly addressed in #2074

**Pull request closed without merging**
