### PR TITLE
Simplify vector extraction

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by tgymnich** [comment]
Does this fix #643?

**Comment by wsmoses** [comment]
Haven't tested, but at least am partially hoping.

**Comment by tgymnich** [comment]
Just tested. It doesn't fix it.

**Comment by wsmoses** [comment]
Alas, well this is still useful for both performance and reducing the amount of LLVM we produce.

**Review by tgymnich — APPROVED** [review]

**Pull request merged**
