### PR TITLE
[BLAS] fix row transpose arg

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by wsmoses** [comment]
@ZuseZ4 @gbaraldi this did not resolve the segfault of the test. Was this the correct fix ?

**Comment by ZuseZ4** [comment]
I need to look at the Fortran code again, I think it might miss a bit.

**Comment by ZuseZ4** [comment]
Found a second bug for gemv

**Comment by ZuseZ4** [comment]
should be a strict improvement, so let's merge.
gemm (alpha, beta) might need more adjustments, but we can do that in a follow-up pr.

**Review by ZuseZ4 — APPROVED** [review]

**Pull request merged**
